sudo: required
dist: trusty
services:
- docker
install:
- docker build -t test .
script:
- docker run -ti test /bin/true
- docker run -ti test /bin/bash --version
- docker run -ti test pacman -S --noconfirm ripgrep-amylum
notifications:
  email: false
  slack:
    secure: I2GF4wJnf8m7w1XS/WNP9E9NWJ+SqzoTeKivid+7tI8p+Y4J1b7oD8bHutVXvo5+iTcPh9UQd4t3+k1UK7DuYFsALJev6hspvvFQdkwfyXNDwuj3S1lsSJ3eld36+WiH8KqNJMq1p/jcuB7gtwHySE0tL50oHyRPNzLhZFiNQ2tv63vqg1xJGZAj/z/4YWfCWlAAzF4oXzioD154gMtxPXQuWeqMKyd7DX1GY862DH3cEBu/qP62ZXnVO9vg+ZQhmBOOg5SZSnHw9bp+FHYBteo7r8QQw7YCedE5IfyDC+uPIwXGGKxPIn/VeT1s4KF18gw69rWWdBzh3t4NbMow+jM4m0e3TuvjmwxzUz3r2DFSDWnOAgt6p8g4A6EUXGCUmbjvSKH6nnyGKU0B7HPvC61qPV8uYJzgPoI5wv5Cd/Hk5FoYjuXTo/j5g/C9LoL/QR9wnSezh+QijAfcpVmUxs03n6w2l8/wliH3iTHyubqwc7SXmODDDIlRuVhtu7/ns3/O6aIcnFCT1652ICe4/X3FwcJ02ofpC6lRIZbGvYn7Jai9ZUkEfyJuLs6VkCZPnOB3jprTlM4q80vPXXAg/ZaRMRV5ul2mfGer9Nd5TNyVYK0l++Ag/t6s5t0F8ClU/haxBnc1uZXHCW4HSVI7SiD63IprB18cV0SXl/PLPVQ=
